modules:
  - name: application
  - name: react_ujs
paths:
  # react library<% if (includeReactAddons) { %>
  'react': 'react/react-with-addons'<% } else { %>
  'react': 'react/react'<% } %>
  'react_ujs': 'react_ujs'
  # require director to handle routing on client-side
  'director': 'director/build/director'<% if (includeSuperagent) { %>
  # REST wrapper
  'superagent': 'superagent/superagent'<% } %>
  # require jquery library
  'jquery': 'jquery'
  'jquery_ujs': 'jquery_ujs'<% if (includeLodash) { %>
  # require lodash
  'lodash': 'lodash/lodash'<% } %>
  # bootstrap library
  'bootstrap': 'bootstrap-sprockets'
shim:
  'react':
    exports: 'React'<% if (includeLodash) { %>
  'lodash':
    exports: '_'<% } %>
  'jquery_ujs': ['jquery']
  'director':
    exports: 'Router'
  'bootstrap': ['jquery']
