paths:
  # react library<% if (includeReactAddons) { %>
  'react-with-addons': 'react/react-with-addons'<% } else { %>
  'react': 'react/react'<% } %>
  # require director to handle routing on client-side
  'director': 'director/build/director'<% if (includeSuperagent) { %>
  # REST wrapper
  'superagent': 'superagent/superagent'<% } %>
  # require jquery library
  'jquery': 'jquery/dist/jquery'<% if (includeLodash) { %>
  # require lodash
  'lodash': 'lodash/dist/lodash'<% } %>
  # bootstrap library
  'bootstrap': 'bootstrap-sprockets'
shim:<% if (includeReactAddons) { %>
  'react-with-addons':
    exports: 'React'<% } else { %>
  'react':
    exports: 'React'<% } %><% if (includeLodash) { %>
  'lodash':
    exports: '_'<% } %>
  'director':
    exports: 'Router'
  'bootstrap': ['jquery']
