# twitter bootstrap
gem 'bootstrap-sass'
# auto prefixer
gem 'autoprefixer-rails'
# bower dependencies manager for rails
gem 'bower-rails'<% if (includeModernizr) { %>
# modernizr
gem 'modernizr-rails', '~> 2.7.1'<% } %><% if (includeMongodb) { %>
# mongoid
gem 'mongoid'<% } %>
# rspec
gem 'rspec'
group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem 'meta_request'
end
# react jsx compile
gem 'react-rails'
# requirejs
gem 'requirejs-rails'<% if (includeButtonCss) { %>
# button sass
gem 'compass-rails'<% } %><% if (includeFontAwesome) { %>
# font awesome
gem 'font-awesome-rails'<% } %><% if (includeLiveReload) { %>
# livereload using guard server
group :development do
  gem 'guard'
  gem 'guard-livereload', require: false
end<% } %><% if (includeGrape) { %>
# grape api
gem 'grape-entity'
gem 'grape'<% } %><% if (includeRubyRacer) { %>
# embed the V8 Javascript Interpreter into Ruby
gem 'therubyracer', platforms: :ruby<% } %>
