# bower dependencies manager for rails
gem 'bower-rails'<% if (includeModernizr) { %>
# modernizr
gem 'modernizr-rails', '~> 2.7.1'<% } %>
# react jsx compile
gem 'react-rails'
# requirejs
gem 'requirejs-rails'<% if (includeButtonCss) { %>
# button sass
gem 'compass-rails'<% } %><% if (includeFontAwesome) { %>
# font awesome
gem 'font-awesome-rails'<% } %><% if (includeLiveReload) { %>
# livereload using guard server
group :development do
  gem 'guard'
  gem 'guard-livereload', require: false
end<% } %>
